import "./globals.css";
import React from "react";
import { Content, Inter } from "next/font/google";
import { Cart, Footer, Footer1, HeroBanner } from "@/Components";
import { NavBar } from "@/Components";
import {
  GlobalStateContext,
  useGlobalState,
} from "./Context/StateContextStore";
import { Toast } from "react-toastify/dist/components";
import { Toaster } from "react-hot-toast";
import Router, { useRouter } from "next/navigation";
import MobNav from "@/Components/MobNav";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 



{
  return (
    <html lang="en">
      <GlobalStateContext>
        <body className={inter.className}>
          <main>
            <div className="flex mt-10 ml-20 lg:space-x-8 sm:space-x-0">
              <HeroBanner />
              <NavBar  />
              <Cart />

            </div>

            <Toaster />
            {children}

            <div className="mt-40">
              <Footer></Footer>
            </div>
            <hr className=" line border-1 w-full border-black " />
            <Footer1></Footer1>
          </main>
        </body>
      </GlobalStateContext>
    </html>
  );
}
